name: Mark Vorenkamp
favicon: null
layout_spectrum: 0.22351775574497879
typography_spectrum: 0.950818725861609
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3842489803209901
  lightness: 0.5209168423898518
  saturation: 0.7473372628446668
  rhythmicContrast: 0.48581470223143697
purpose: []
