name: Mark Vorenkamp
favicon: null
layout_spectrum: 0.90845
typography_spectrum: 0.76687
title: Ghostwriter - Content Marketer - Copywriter
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7c7f73'
    - '#a8a89b'
    - '#003080'
    - '#2b1e16'
    - '#0052b5'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
